export const FETCH_PLACE = 'FETCH_PLACE';
export const FETCH_PLACE_SUCCESS = 'FETCH_PLACE_SUCCESS';
export const FETCH_PLACE_FAILED = 'FETCH_PLACE_FAILED';
//////////////
export const FETCH_SPENDING = 'FETCH_SPENDING';
export const FETCH_SPENDING_SUCCESS = 'FETCH_SPENDING_SUCCESS';
export const FETCH_SPENDING_FAILED = 'FETCH_SPENDING_FAILED';

//////////////////////////
export const FETCH_EARNING = 'FETCH_EARNING';
export const FETCH_EARNING_SUCCESS = 'FETCH_EARNING_SUCCESS';
export const FETCH_EARNING_FAILED = 'FETCH_EARNING_FAILED';
////////////

export const DELETE_SPENDING = 'DELETE_SPENDING';
export const DELETE_SPENDING_SUCCESS = 'DELETE_SPENDING_SUCCESS';
export const DELETE_SPENDING_FAILED = 'DELETE_SPENDING_FAILED';

export const DELETE_EARNING = 'DELETE_EARNING';
export const DELETE_EARNING_SUCCESS = 'DELETE_EARNING_SUCCESS';
export const DELETE_EARNING_FAILED = 'DELETE_EARNING_FAILED';
///////////////

export const UPDATE_SPENDING = 'UPDATE_SPENDING';
export const UPDATE_SPENDING_SUCCESS = 'UPDATE_SPENDING_SUCCESS';
export const UPDATE_SPENDING_FAILED = 'UPDATE_SPENDING_FAILED';

//////////////
export const UPDATE_EARNING = 'UPDATE_EARNING';
export const UPDATE_EARNING_SUCCESS = 'UPDATE_EARNING_SUCCESS';
export const UPDATE_EARNING_FAILED = 'UPDATE_EARNING_FAILED';

////////////////

export const FETCH_ALL_SE = 'FETCH_ALL_SE';
export const FETCH_ALL_SE_SUCCESS = 'FETCH_ALL_SE_SUCCESS';
export const FETCH_ALL_SE_FAILED = 'FETCH_ALL_SE_FAILED';

////////////////// insert spending

export const INSERT_SPENDING = 'INSERT_SPENDING';
export const INSERT_SPENDING_SUCCESS = 'INSERT_SPENDING_SUCCESS';
export const INSERT_SPENDING_FAILED = 'INSERT_SPENDING_FAILED';

////////////// insert earning
export const INSERT_EARNING = 'INSERT_EARNING';
export const INSERT_EARNING_SUCCESS = 'INSERT_EARNING_SUCCESS';
export const INSERT_EARNING_FAILED = 'INSERT_EARNING_FAILED';

/////////////////

export const FETCH_CUSTOMDATA = 'FETCH_CUSTOMDATA';
export const FETCH_CUSTOMDATA_SUCCESS = 'FETCH_CUSTOMDATA_SUCCESS';
export const FETCH_CUSTOMDATA_FAILED = 'FETCH_CUSTOMDATA_FAILED';

///////////////
// screen list custom

export const FETCH_LIST_CUSTOM = 'FETCH_LIST_CUSTOM';
export const FETCH_LIST_CUSTOM_SUCCESS = 'FETCH_LIST_CUSTOM_SUCCESS';
export const FETCH_LIST_CUSTOM_FAILED = 'FETCH_LIST_CUSTOM_FAILED';

// screen edit custom
export const UPDATE_CUSTOM = 'UPDATE_CUSTOM';
export const UPDATE_CUSTOM_SUCCESS = 'UPDATE_CUSTOM_SUCCESS';
export const UPDATE_CUSTOM_FAILED = 'UPDATE_CUSTOM_FAILED';

export const DELETE_CUSTOM = 'DELETE_CUSTOM';
export const DELETE_CUSTOM_SUCCESS = 'DELETE_CUSTOM_SUCCESS';
export const DELETE_CUSTOM_FAILED = 'DELETE_CUSTOM_FAILED';

// screen add custom

export const ADD_CUSTOM = 'ADD_CUSTOM';
export const ADD_CUSTOM_SUCCESS = 'ADD_CUSTOM_SUCCESS';
export const ADD_CUSTOM_FAILED = 'ADD_CUSTOM_FAILED';

// screen list product

export const FETCH_LIST_PRODUCT = 'FETCH_LIST_PRODUCT';
export const FETCH_LIST_PRODUCT_SUCCESS = 'FETCH_LIST_PRODUCT_SUCCESS';
export const FETCH_LIST_PRODUCT_FAILED = 'FETCH_LIST_PRODUCT_FAILED';

// screen edit product

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';

// screen add place

export const ADD_PLACE = 'ADD_PLACE';

export const DELETE_PLACE = 'DELETE_PLACE';

export const UPDATE_PLACE = 'UPDATE_PLACE';
