 // screen home
export const  FETCH_PLACE = "FETCH_PLACE" 
export const  FETCH_PLACE_SUCCESS = "FETCH_PLACE_SUCCESS" 
export const  FETCH_PLACE_FAILED = "FETCH_PLACE_FAILED" 

// screen list custom

export const FETCH_LIST_CUSTOM = "FETCH_LIST_CUSTOM"
export const FETCH_LIST_CUSTOM_SUCCESS = "FETCH_LIST_CUSTOM_SUCCESS"
export const FETCH_LIST_CUSTOM_FAILED = "FETCH_LIST_CUSTOM_FAILED"


// screen edit custom
export const UPDATE_CUSTOM = "UPDATE_CUSTOM"
export const UPDATE_CUSTOM_SUCCESS = "UPDATE_CUSTOM_SUCCESS"
export const UPDATE_CUSTOM_FAILED = "UPDATE_CUSTOM_FAILED"

export const DELETE_CUSTOM = "DELETE_CUSTOM"
export const DELETE_CUSTOM_SUCCESS = "DELETE_CUSTOM_SUCCESS"
export const DELETE_CUSTOM_FAILED = "DELETE_CUSTOM_FAILED"


// screen add custom

export const ADD_CUSTOM = "ADD_CUSTOM"
export const ADD_CUSTOM_SUCCESS = "ADD_CUSTOM_SUCCESS"
export const ADD_CUSTOM_FAILED = "ADD_CUSTOM_FAILED"


// screen list product

export const FETCH_LIST_PRODUCT = "FETCH_LIST_PRODUCT"
export const FETCH_LIST_PRODUCT_SUCCESS = "FETCH_LIST_PRODUCT_SUCCESS"
export const FETCH_LIST_PRODUCT_FAILED = "FETCH_LIST_PRODUCT_FAILED"

// screen edit product

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"


// screen add place 

export const ADD_PLACE = "ADD_PLACE";

export const DELETE_PLACE = "DELETE_PLACE";
